### ISSUE TITLE
No download available, and later no rakuyomi open available

### ISSUE THREAD

**Issue by FernandoRApud** [hanatsumi/rakuyomi#118]
**Describe the bug**

When im trying to fetch/download a manga chapter, this suddenly shows an error. If i touch the X on the corner and try to open Rakuyomi again, this never open again until i re open KOReader. The error is something like "client error (SendRequest)"

**To Reproduce**

1. Go to 'Rakuyomi'
2. Add a source
3. Enter the source
4. Try to download a chapter
5. Fail and quit
6. Try to open again Rakuyomi
7. Bug appear.

**Expected behavior**

Can download a chapter. Or at least, if the download fail, can open Rakuyomi again.

**Environment:**

 - Device: [e.g. Kindle Paperwhite 11]
 - KOReader version: [v2025.04-1-g9dbcde430_2025-04-09]
 - Source name (if applicable): [TuMangaOnline]

**`crash.log` (if applicable)**

[crash.log](https://github.com/user-attachments/files/19688572/crash.log)

**Comment by IndyGibb** [comment]
I have this same bug, KOReader version 2025.4, Kindle 10th Generation with firmware version 5.17.1.0.3.

[crash.log](https://github.com/user-attachments/files/19689457/crash.log)

**Comment by hanatsumi** [comment]
@FernandoRApud Should be fixed in v1.13.0

@IndyGibb This looks like a different issue with a specific source, can you pinpoint down which source causes this?

**Comment by IndyGibb** [comment]
I'll do a fresh install and see if I can pinpoint any soures that might cause issues.

**Comment by IndyGibb** [comment]
With the newest version I'm not having the issue of it disappearing, but after a bit I am not able to find any manga while searching. Just to see if the searches worked, I searched for Tower of God on webtoon (since I know it exists there), and it came up. I tried adding more sources, but then I stopped getting results for anything. I uninstalled them all and am still getting no results.

I do also have the personal issue of not knowing which sources I can expect to find what on but that's more of a personal problem.

[crash.log](https://github.com/user-attachments/files/19721058/crash.log)
